/*
 * The MIT License
 *
 * Copyright 2017 Acer.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package detektorklicu;

import java.awt.Color;
import java.awt.Dimension;
import java.beans.PropertyChangeEvent;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingWorker;
import javax.swing.table.TableModel;

/**
 *
 * @author Acer
 */
public class DetectionPanel extends javax.swing.JPanel {

    /**
     * Creates new form DetectionPanel
     * @param detection 
     */
    public DetectionPanel(Detection detection, MainWindow parent) {
        this.detection = detection;
        this.canvas = new Canvas(detection.getOriginal());
        this.parent = parent;
        initComponents();
        
        imageScrollPane.setViewportView(canvas);
        tableScrollPane.setVisible(false);
        progressPanel.setVisible(false);
        
        detection.getImage().setWorker(worker);
        worker.addPropertyChangeListener(this::workerChangeListener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        tableScrollPane = new javax.swing.JScrollPane();
        regionsTable = new javax.swing.JTable();
        imageScrollPane = new javax.swing.JScrollPane();
        progressPanel = new javax.swing.JPanel();
        progressBar = new javax.swing.JProgressBar();
        cancelBtn = new javax.swing.JToggleButton();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        splitPane.setDividerLocation(splitPane.getHeight());
        splitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        tableScrollPane.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                tableScrollPaneComponentResized(evt);
            }
        });

        regionsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        regionsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regionsTableMouseClicked(evt);
            }
        });
        tableScrollPane.setViewportView(regionsTable);

        splitPane.setBottomComponent(tableScrollPane);
        splitPane.setLeftComponent(imageScrollPane);

        progressBar.setMaximum(1000);
        progressBar.setToolTipText("");
        progressBar.setMinimumSize(new java.awt.Dimension(100, 25));
        progressBar.setString("backgroundOperation");
        progressBar.setStringPainted(true);

        cancelBtn.setText("cancelBtn");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout progressPanelLayout = new javax.swing.GroupLayout(progressPanel);
        progressPanel.setLayout(progressPanelLayout);
        progressPanelLayout.setHorizontalGroup(
            progressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(progressPanelLayout.createSequentialGroup()
                .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelBtn))
        );
        progressPanelLayout.setVerticalGroup(
            progressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cancelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
            .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
            .addComponent(progressPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(progressPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        //if(regionsTableHidden) hideTable();
    }//GEN-LAST:event_formComponentResized

    private void tableScrollPaneComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tableScrollPaneComponentResized
        //tableHidden = false;
        //fillTable();
    }//GEN-LAST:event_tableScrollPaneComponentResized

    private void regionsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regionsTableMouseClicked
        if(evt.getClickCount() >= 2) showRegionDetail();
    }//GEN-LAST:event_regionsTableMouseClicked

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        worker.cancelJob();
    }//GEN-LAST:event_cancelBtnActionPerformed
    
    private void workerChangeListener(PropertyChangeEvent e){
        if("state".equals(e.getPropertyName())){
            progressPanel.setVisible(e.getNewValue() == SwingWorker.StateValue.STARTED);
        }
        else if("progressName".equals(e.getPropertyName())){
            progressBar.setString(worker.getProgressText((String)e.getNewValue()));
        }
        else if("progressValue".equals(e.getPropertyName())){
            progressBar.setValue((int)e.getNewValue());
        }
    }
    
    public void showRegionsTable(boolean b) {
        tableScrollPane.setVisible(b);
        if(b) {
            splitPane.setDividerLocation(getHeight()/4*3);
            worker.runInBackground(this::fillTable);// (0)->{fillTable();});
            //(<any> 0)->{fillTable();}
        }
    }
    
    public void toggleRegionsTable(){
        showRegionsTable(!isRegionsTableShown());
    }
    
    private Region getSelectedRegion(){
        int row = regionsTable.getSelectedRow();
        if(row >= 0){
            TableModel model = regionsTable.getModel();
            if(model instanceof RegionsTableModel){
                return ((RegionsTableModel) model).getRegionAt(row);
            }
        }
        return null;
    }
    
    public boolean isSelectedRegion(){
        return false;
    }

    public boolean isRegionsTableShown() {
        return tableScrollPane.isVisible();
    }
    
    private void fillTable(){
        //worker.runInBackground(()->{
            regionsTable.setModel(detection.getImage().getRegionsTableModel());

            regionsTable.getColumnModel().getColumn(0).setWidth(30);
            regionsTable.getColumnModel().getColumn(3).setWidth(60);
        //});
    }
    
    public void viewOriginalSize() {
        Dimension d = new Dimension(detection.getOriginal().getWidth(), detection.getOriginal().getHeight());
        canvas.setPreferredSize(d);
        canvas.setSize(d);
    }
    
    public void viewScalledSize() {
        canvas.setPreferredSize(null);
        canvas.setSize(imageScrollPane.getSize());
    }
    
    /*public void detectRegions() {
        detection.startDetection();
    }*/
    
    public void showLabels() {
        worker.runInBackground(()->{
            canvas.setImage(detection.getLabelsImage());
            canvas.repaint();
        });
    }
    
    public void showBackground() {
        worker.runInBackground(()->{
            canvas.setImage(detection.getBackgroundImage());
            canvas.repaint();
        });
    }
    
    public void showOriginal() {
        canvas.setImage(detection.getOriginal());
        canvas.repaint();
    }
    
    public void showRegions() {
        worker.runInBackground(()->{
            canvas.displayRegions(detection.getImage().getRegionsPolygons(),Color.blue);
            canvas.repaint();
        });
    }
    
    public void hideRegions() {
        canvas.hideRegions();
        canvas.repaint();
    }
    
    public void toggleRegions() {
        if(canvas.showingRegions()) hideRegions();
        else showRegions();
    }
    
    public void showRegionDetail() {
        Region region = getSelectedRegion();
        if(region == null) return;
        StringBuilder sb = new StringBuilder();
        sb.append("thetha=").append(region.getOrientation()).append("\n")
                .append("a=").append(region.getHalfAxisA()).append("\n")
                .append("b=").append(region.getHalfAxisB()).append("\n");
        JOptionPane.showMessageDialog(this, sb.toString(), "Detail", JOptionPane.INFORMATION_MESSAGE);
        canvas.displayRegions(region.getBoundingRectangle(),Color.blue);
        canvas.repaint();
    }
    
    private JTable getRegionsTable() {
        return regionsTable;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton cancelBtn;
    private javax.swing.JScrollPane imageScrollPane;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JPanel progressPanel;
    private javax.swing.JTable regionsTable;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JScrollPane tableScrollPane;
    // End of variables declaration//GEN-END:variables

    private Detection detection;
    private Canvas canvas;
    private MainWindow parent;
    private QueuedWorker worker = new QueuedWorker();
}
